//! DNS：`/etc/resolv.conf` 里配置的域名服务器。
//!
//! 只读这一个文件，解析规则跟着 `resolv.conf(5)` 走最小一致的那几条：
//!
//! - 关键字**大小写敏感**：glibc 的 `__res_vinit` 就是按小写字面量比的，
//!   `Nameserver` 它不认，我们也不认（认了反而和真实行为不一致）；
//! - `#` 与 `;` 起注释作用（`res_init` 两个都认），行首整行注释直接跳过；
//! - 只取关键字后**第一个**字段，多余的字段是 glibc 也会忽略的东西；
//! - 关键字后面必须有空白：`nameserver-foo` 不是关键字。
//!
//! 按文件顺序原样列出、不排序也不去重。这个顺序就是解析器尝试的顺序，
//! 换一个顺序输出会让人以为优先级变了；两台机器配了同样的地址但顺序不同，
//! 本来就是两回事。
//!
//! 读 `127.0.0.53` 这类本地中转的做法是**有条件的**：只有在
//! `/etc/resolv.conf` 里一个真实地址都没有、**全是回环 stub** 时，才改读
//! systemd-resolved 维护的 `/run/systemd/resolve/resolv.conf`（那里面写的是真实上游）。
//! 判据必须这么严：只要出现过任何一个非 stub 地址，那份配置就是权威的，
//! 拿 resolved 的文件去覆盖它反而会读错。
//! 回退文件不存在、或里面也没有 `nameserver` 时**保留原来那份**——
//! stub 地址至少说明这台机器上有 resolved 在跑，比什么都不显示有用。
//!
//! 没有 `nameserver` 行、或者文件不存在 → 无数据。

use crate::collectors::read;
use crate::core::collector::{CollectError, Collector, Context};
use crate::core::info::Info;

/// 配置文件。
const CONF: &str = "/etc/resolv.conf";
/// 关键字。
const KEYWORD: &str = "nameserver";
/// systemd-resolved 自己维护的那份：里面的 `nameserver` 是真实上游。
const RESOLVED: &str = "/run/systemd/resolve/resolv.conf";

/// 回环 stub 地址：配置里只剩这些，等于一个真答案都没有。
///
/// `127.0.0.53` 是 systemd-resolved 的 stub 监听地址；`127.0.0.1` 是同类东西的
/// 另一种写法（dnsmasq、unbound 这些本地转发器）；`::1` 是 IPv6 版的同一回事。
const STUBS: [&str; 3] = ["127.0.0.53", "127.0.0.1", "::1"];

/// DNS。
pub struct Dns;

impl Collector for Dns {
    fn name(&self) -> &'static str {
        "dns"
    }

    fn collect(&self, _ctx: &Context) -> Result<Vec<Info>, CollectError> {
        let Some(text) = read::text(CONF)? else {
            // 文件不存在不是错误：这类机器（容器、resolvconf 还没写）
            // 就是没有配置，报一个「读不到 DNS」只会吓人。
            return Ok(Vec::new());
        };

        let mut servers = parse_resolv_conf(&text);
        if all_stubs(&servers) {
            // 只有这种情况才多读一个文件：别的时候这份配置就是权威的。
            servers = prefer_upstream(servers, read::text(RESOLVED)?.as_deref());
        }
        if servers.is_empty() {
            return Ok(Vec::new());
        }

        let value = servers.join(", ");
        Ok(vec![
            Info::new(self.name(), "DNS", value).with_variable("count", servers.len().to_string()),
        ])
    }
}

/// 全是回环 stub 地址吗。
///
/// 空表返回 `false`：一个地址都没有不叫「全是 stub」，那是真的没配。
#[must_use]
fn all_stubs(servers: &[String]) -> bool {
    !servers.is_empty() && servers.iter().all(|server| is_stub(server))
}

/// 是不是回环 stub 地址。大小写不敏感（IPv6 地址可能写成大写）。
#[must_use]
fn is_stub(server: &str) -> bool {
    let server = server.to_ascii_lowercase();
    STUBS.iter().any(|stub| server == *stub)
}

/// 手里这份全是 stub 时，换成 resolved 那份。
///
/// 换不成（`resolved` 读不到，或里面也没有 `nameserver`）就把原来那份原样还回去——
/// 那时 stub 地址仍是比「什么都没有」有用的信息。
fn prefer_upstream(servers: Vec<String>, resolved: Option<&str>) -> Vec<String> {
    if !all_stubs(&servers) {
        return servers;
    }

    match resolved.map(parse_resolv_conf) {
        Some(upstream) if !upstream.is_empty() => upstream,
        _ => servers,
    }
}

/// 取出所有 `nameserver` 后面的地址，保持文件顺序。
fn parse_resolv_conf(text: &str) -> Vec<String> {
    let mut servers = Vec::new();

    for line in text.lines() {
        let mut fields = line.split_whitespace();
        if fields.next() != Some(KEYWORD) {
            continue;
        }

        let Some(address) = fields.next() else {
            continue;
        };
        // `nameserver # 被注释掉的地址`：`#` 是那行的注释开头，
        // 不是地址，整行等于没写。
        if address.starts_with('#') || address.starts_with(';') {
            continue;
        }

        servers.push(address.to_owned());
    }

    servers
}

#[cfg(test)]
mod tests {
    use super::*;

    /// 本机 `/etc/resolv.conf` 的形状（NetworkManager 写的）。
    const FIXTURE: &str = "\
# Generated by NetworkManager
nameserver 192.168.1.1
nameserver fe80::1%enp5s4u1u3c2
";

    #[test]
    fn reads_the_servers_in_file_order() {
        assert_eq!(
            parse_resolv_conf(FIXTURE),
            vec!["192.168.1.1", "fe80::1%enp5s4u1u3c2"]
        );
    }

    #[test]
    fn comments_are_ignored() {
        // 行首注释、行尾注释、以及「整行都被注释掉」三种。
        let text = "\
# nameserver 1.1.1.1
nameserver 8.8.8.8 # 谷歌的
; nameserver 9.9.9.9
nameserver # 只有注释
";
        assert_eq!(parse_resolv_conf(text), vec!["8.8.8.8"]);
    }

    #[test]
    fn extra_fields_after_the_address_are_dropped() {
        // glibc 看完第一个字段就走，后面写了什么它都不管。
        assert_eq!(
            parse_resolv_conf("nameserver 1.1.1.1 2.2.2.2\n"),
            vec!["1.1.1.1"]
        );
    }

    #[test]
    fn the_keyword_is_case_sensitive_and_needs_whitespace() {
        // 这两条都是为了和 glibc 的实际行为一致，不是洁癖。
        assert!(parse_resolv_conf("Nameserver 1.1.1.1\n").is_empty());
        assert!(parse_resolv_conf("nameserver-foo 1.1.1.1\n").is_empty());
        assert!(
            parse_resolv_conf("nameserver\n").is_empty(),
            "只有关键字不算"
        );
    }

    #[test]
    fn leading_whitespace_is_tolerated() {
        assert_eq!(
            parse_resolv_conf("  nameserver\t1.1.1.1\n"),
            vec!["1.1.1.1"]
        );
    }

    #[test]
    fn a_conf_without_servers_is_no_data() {
        assert!(parse_resolv_conf("").is_empty());
        assert!(parse_resolv_conf("options timeout:2\nsearch lan\n").is_empty());
    }

    // -----------------------------------------------------------------------
    // systemd-resolved 回退：fixture 直接给两份文件的内容，不依赖真机
    // -----------------------------------------------------------------------

    /// `/etc/resolv.conf` 只剩 stub 时读到的样子。
    const STUB_CONF: &str = "nameserver 127.0.0.53\n";
    /// resolved 维护的那份里的真实上游。
    const RESOLVED_CONF: &str = "nameserver 192.168.1.1\nnameserver 8.8.8.8\n";

    #[test]
    fn a_stub_only_conf_falls_back_to_the_resolved_file() {
        let servers = prefer_upstream(parse_resolv_conf(STUB_CONF), Some(RESOLVED_CONF));

        assert_eq!(servers, vec!["192.168.1.1", "8.8.8.8"]);
    }

    #[test]
    fn every_stub_spelling_triggers_the_fallback() {
        for stub in STUBS {
            let servers = prefer_upstream(
                parse_resolv_conf(&format!("nameserver {stub}\n")),
                Some(RESOLVED_CONF),
            );
            assert_eq!(
                servers,
                vec!["192.168.1.1", "8.8.8.8"],
                "{stub} 也是 stub，该回退"
            );
        }
    }

    #[test]
    fn a_real_address_does_not_trigger_the_fallback() {
        // 本机就是这样：resolv.conf 里写着真实地址。resolved 的文件（哪怕存在、
        // 哪怕写的是别的地址）都不该覆盖它。
        let servers = prefer_upstream(
            parse_resolv_conf("nameserver 192.168.1.1\n"),
            Some("nameserver 9.9.9.9\n"),
        );

        assert_eq!(servers, vec!["192.168.1.1"]);
    }

    #[test]
    fn one_real_address_among_stubs_skips_the_fallback() {
        // 混合的情况最容易写反：只要有一个真地址，这份配置就是权威的。
        let servers = prefer_upstream(
            parse_resolv_conf("nameserver 127.0.0.53\nnameserver 10.0.0.2\n"),
            Some(RESOLVED_CONF),
        );

        assert_eq!(servers, vec!["127.0.0.53", "10.0.0.2"]);
    }

    #[test]
    fn without_the_resolved_file_the_stub_is_kept() {
        // 回退文件不在、或里面没有 nameserver：保留 stub，不要变成无数据——
        // 它至少说明这台机器上有 resolved 在跑。
        for missing in [None, Some("# 空的\n")] {
            let servers = prefer_upstream(parse_resolv_conf(STUB_CONF), missing);
            assert_eq!(servers, vec!["127.0.0.53"], "实际输入：{missing:?}");
        }
    }

    #[test]
    fn an_empty_list_is_not_all_stubs() {
        // 「一个地址都没有」不叫「全是 stub」，否则会去读一个根本用不上的文件。
        assert!(!all_stubs(&[]));
        assert!(all_stubs(&["127.0.0.53".to_owned()]));
        assert!(!all_stubs(&["127.0.0.53".to_owned(), "1.1.1.1".to_owned()]));
        assert!(is_stub("::1"));
        assert!(!is_stub("::2"));
    }

    #[test]
    fn collects_on_this_machine_if_resolv_conf_has_servers() {
        let entries = Dns.collect(&Context::for_tests()).unwrap();

        // 没配 DNS 的机器（或干净的容器）这里就是空。
        match entries.first() {
            None => {}
            Some(info) => {
                assert_eq!(info.key, "DNS");
                assert!(!info.value.is_empty());
                assert!(!info.value.contains('\n'), "值必须是一行：渲染器按行排版");
            }
        }
    }

    #[test]
    fn the_value_matches_the_file_on_this_machine() {
        // 把模块输出和直接解析文件的结果对一遍（文件不在就跳过）。
        let Ok(Some(text)) = read::text(CONF) else {
            return;
        };
        // 走和 `collect` 同一条判断：只有全是 stub 时才改读 resolved 那份。
        let mut expected = parse_resolv_conf(&text);
        if all_stubs(&expected) {
            expected = prefer_upstream(expected, read::text(RESOLVED).unwrap_or(None).as_deref());
        }
        let expected = expected.join(", ");
        let entries = Dns.collect(&Context::for_tests()).unwrap();

        assert_eq!(
            entries.first().map(|info| info.value.clone()),
            (!expected.is_empty()).then_some(expected)
        );
    }
}
